
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/canonical/maas-terraform-modules.git//modules/maas-config"
}

include "root" {
  path = find_in_parent_folders("terragrunt.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The MAAS URL in the format of: http://127.0.0.1:5240/MAAS
  # Type: string
  maas_url = "" # TODO: fill in value

  # Description: The MAAS API key
  # Type: string
  maas_key = "" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description:
  #       The URL of the boot source to synchronize OS images from
  #       This needs to be a simple streams server
  #   
  # Type: string
  # image_server_url = "http://images.maas.io/ephemeral-v3/stable/"

  # Description:
  #       Configure MAAS to download these images immediately.
  #       Each key is the release name and the value is a map of
  #       architectures and - optionally - sub-architectures
  #   
  # Type: map
  # boot_selections = {}

  # Description:
  #       A map of MAAS configuration settings, where key is the setting name and
  #       value is the setting desired value
  #   
  # Type: map
  # maas_config = {}

  # Description:
  #       A map of package repositories to supply to MAAS deployed machines, where
  #       key is the repository name and value is a map of package repository
  #       settings
  #   
  # Type: map
  # package_repositories = {}

  # Description:
  #       A map of tags to create, where key is the tag name and value is a map of
  #       tag attributes
  #   
  # Type: map
  # tags = {}

  # Description:
  #       A map of DNS domains to create, where key is the domain name and value is a
  #       map of domain attributes
  #   
  # Type: map
  # domains = {}

  # Description:
  #       A map of DNS domain records to create, where key is the domain name and
  #       value is a set domain records. Each domain record is a map of domain record
  #       attributes
  #   
  # Type: map
  # domain_records = {}

  # Description:
  #       A set of node scripts to create, where each set item points to the script
  #       file path relative to node_scripts_location
  #   
  # Type: set
  # node_scripts = []

  # Description: The path in disk where node script files are located
  # Type: string
  # node_scripts_location = "."

}
