
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/canonical/maas-terraform-modules.git//modules/juju-bootstrap?ref=main"
}

include "root" {
  path = find_in_parent_folders("root.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The API endpoint URL that Juju should use to communicate to LXD
  # Type: string
  lxd_address = "" # TODO: fill in value

  # Description: The LXD trust token that Juju should use to authenticate to LXD
  # Type: string
  lxd_trust_token = "" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The Juju cloud name. Juju will use this name to refer to the Juju cloud you are creating
  # Type: string
  # cloud_name = "maascloud"

  # Description: The LXD project that Juju should use for the controller resources
  # Type: string
  # lxd_project = "default"

  # Description: Map of model configuration defaults to pass to juju bootstrap (e.g., http-proxy, https-proxy, no-proxy, apt-http-proxy, etc.)
  # Type: map
  # model_defaults = {}

  # Description: Additional flags for destroying the controller. See the [Juju provider docs](https://documentation.ubuntu.com/terraform-provider-juju/v1.3.0-rc1/reference/terraform-provider/resources/controller/#nested-schema-for-destroy-flags) for details on available flags or the [Juju docs](https://documentation.ubuntu.com/juju/3.6/howto/manage-controllers/#destroy-a-controller) for more information.
  # Type: object
  # destroy_flags = {"destroy_all_models":true,"force":true}

  # Description: Constraints for the controller machine
  # Type: object
  # bootstrap_constraints = {"cores":"2", "mem":"4G", "root-disk":"10G", "arch":"amd64"}

}
