
# This is a Terragrunt unit generated by Gruntwork Boilerplate (https://github.com/gruntwork-io/boilerplate).
terraform {
  source = "git::https://github.com/canonical/maas-terraform-modules.git//modules/juju-bootstrap"
}

include "root" {
  path = find_in_parent_folders("terragrunt.hcl")
}

inputs = {
  # --------------------------------------------------------------------------------------------------------------------
  # Required input variables
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The API endpoint URL that Juju should use to communicate to LXD
  # Type: string
  lxd_address = "" # TODO: fill in value

  # Description: The LXD trust token that Juju should use to authenticate to LXD
  # Type: string
  lxd_trust_token = "" # TODO: fill in value


  # --------------------------------------------------------------------------------------------------------------------
  # Optional input variables
  # Uncomment the ones you wish to set
  # --------------------------------------------------------------------------------------------------------------------

  # Description: The Juju cloud name. Juju will use this name to refer to the Juju cloud you are creating
  # Type: string
  # cloud_name = "maascloud"

  # Description: The LXD project that Juju should use for the controller resources
  # Type: string
  # lxd_project = "default"

  # Description: Map of model configuration defaults to pass to juju bootstrap (e.g., http-proxy, https-proxy, no-proxy, apt-http-proxy, etc.)
  # Type: map
  # model_defaults = {}

}
